# Generated by Django 4.1.7 on 2023-03-30 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Поля автоматически заполняется')),
            ],
            options={
                'verbose_name': 'Ученая степень',
                'verbose_name_plural': 'Ученая степень',
            },
        ),
        migrations.CreateModel(
            name='Academic_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'учебный год',
                'verbose_name_plural': 'учебный год',
            },
        ),
        migrations.CreateModel(
            name='All_job_positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default=2023)),
                ('year2', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default=2023)),
                ('number_order', models.IntegerField(verbose_name='номерр приказа')),
                ('slug', models.SlugField(blank=True, help_text='Поля автоматически заполняется')),
            ],
            options={
                'verbose_name': 'Год выступ и поступ',
                'verbose_name_plural': 'Год выступ и поступ',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя кафедры: ')),
                ('slug', models.SlugField(blank=True, help_text='поля автоматически заполняется')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедра',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название факултета')),
                ('slug', models.SlugField(blank=True, help_text='Поля автоматически заполняется')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультет',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='должность: ')),
                ('slug', models.SlugField(blank=True, help_text='Поля автоматически заполняется')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должность',
            },
        ),
        migrations.CreateModel(
            name='Scientific_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Поля автоматически заполняется')),
            ],
            options={
                'verbose_name': 'научное звание',
                'verbose_name_plural': 'научное звание',
            },
        ),
        migrations.CreateModel(
            name='Universitate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Поля автоматически заполняется')),
            ],
            options={
                'verbose_name': 'Университет',
                'verbose_name_plural': 'Университет',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('first_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('birthday', models.DateField(verbose_name='Дата рождение: ')),
                ('doc_pdf', models.FileField(upload_to='pdf/')),
                ('academic_degree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.academic_degree', verbose_name='Ученая степень')),
                ('academic_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.academic_year', verbose_name='Учебный год')),
                ('all_job_positions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.all_job_positions', verbose_name='Все должности работы')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.department', verbose_name='Кафедра')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.faculty', verbose_name='Факультет')),
                ('job_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.job', verbose_name='Должность')),
                ('scientific_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.scientific_title', verbose_name='научное звание')),
                ('universitate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.universitate', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Персонал',
                'verbose_name_plural': 'Персонал',
            },
        ),
        migrations.AddField(
            model_name='faculty',
            name='universitate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.universitate', verbose_name='Университет'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.faculty', verbose_name='Факультет: '),
        ),
        migrations.AddField(
            model_name='all_job_positions',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.job', verbose_name='Должность'),
        ),
    ]
