# Generated by Django 4.1.7 on 2023-03-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_job_positions',
            name='slug',
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Отечество'),
        ),
    ]
